checks:
  php: true

filter:
  paths:
    - src/*
    - websocket/*

tools:
  external_code_coverage:
    timeout: 600
    runs: 4
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_pdepend: true
  php_loc: true
